// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Generates a personalized follow-up message using AI.
 *
 * - generateFollowUpMessage - A function that generates a follow-up message.
 * - GenerateFollowUpMessageInput - The input type for the generateFollowUpMessage function.
 * - GenerateFollowUpMessageOutput - The return type for the generateFollowUpMessage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateFollowUpMessageInputSchema = z.object({
  contactName: z.string().describe('The name of the contact.'),
  contactDetails: z.string().describe('Additional details about the contact (e.g., email, company).'),
  notes: z.string().describe('Any notes about previous interactions with the contact.'),
  followUpCount: z.number().describe('The number of times you have followed up with this contact.'),
});
export type GenerateFollowUpMessageInput = z.infer<typeof GenerateFollowUpMessageInputSchema>;

const GenerateFollowUpMessageOutputSchema = z.object({
  followUpMessage: z.string().describe('The AI-generated follow-up message.'),
});
export type GenerateFollowUpMessageOutput = z.infer<typeof GenerateFollowUpMessageOutputSchema>;

export async function generateFollowUpMessage(input: GenerateFollowUpMessageInput): Promise<GenerateFollowUpMessageOutput> {
  return generateFollowUpMessageFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateFollowUpMessagePrompt',
  input: {schema: GenerateFollowUpMessageInputSchema},
  output: {schema: GenerateFollowUpMessageOutputSchema},
  prompt: `You are an AI assistant helping to generate personalized follow-up messages for contacts.

  Consider the following information about the contact:
  - Contact Name: {{{contactName}}}
  - Contact Details: {{{contactDetails}}}
  - Previous Notes: {{{notes}}}
  - Follow-Up Count: {{{followUpCount}}}

  Generate a follow-up message that is appropriate and personalized based on the provided information. The message should be concise and professional.
  The message should not be longer than 200 characters.
  Do not include any salutations or closings. (e.g. "Dear Contact Name", "Sincerely")
  Just include the raw message.
  If the Follow-Up Count is 0, make it an initial follow up message.
  If the Follow-Up Count is greater than 0, make it a subsequent follow up message.
  The message should not be repetitive or generic.
  `,
});

const generateFollowUpMessageFlow = ai.defineFlow(
  {
    name: 'generateFollowUpMessageFlow',
    inputSchema: GenerateFollowUpMessageInputSchema,
    outputSchema: GenerateFollowUpMessageOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
